language: haskell

ghc: 
  - '7.6'
  - '7.8'
  - '7.10'

services:
  - mongodb

sudo: required

before_install: 
  - cabal update
  - cabal install cabal-install
  - export PATH="$HOME/.cabal/bin:$PATH"
  - echo "Cabal updated, displaying new version..."
  - cabal -V
  - cabal sandbox init
  - cabal install bnfc
  - sudo pip install hypothesis==1.2
  - sudo pip install requests
  - npm install -g npm-cache

script:
  - cabal configure --enable-tests && cabal build && cabal test
  - sh tests.sh

