language: haskell

ghc: 
  - "8.0"
  - "8.2"

services:
  - mongodb

sudo: required

before_install: 
  - export PATH="$HOME/.cabal/bin:$PATH"
  - cabal install alex
  - cabal install happy
  - cabal install BNFC
  - npm install -g npm
  - sudo pip install virtualenv
  - virtualenv venv
  - source venv/bin/activate
  - sudo apt-get install -y maven

addons:
  apt:
    update: true

script:
  - cabal new-test
  - cabal install
  - bash scripts/testing/end_to_end_tests.sh 0

