language: haskell

ghc: 7.8

services:
  - mongodb

sudo: required

before_install: 
  - cabal update
  - cabal install cabal-install
  - export PATH="$HOME/.cabal/bin:$PATH"
  - echo "Cabal updated, displaying new version..."
  - cabal -V
  - cabal install alex
  - cabal install happy
  - cabal install bnfc
  - npm install -g npm-cache
  - sudo pip install virtualenv
  - virtualenv venv
  - source venv/bin/activate

script:
  - cabal configure --enable-tests && cabal build && cabal test
  - sh scripts/testing/end_to_end_tests.sh

